https://stackoverflow.com/questions/3386259/how-to-make-a-multidimension-numpy-array-with-a-varying-row-size

In [1]:
import numpy as np

In [17]:
x = np.array([[11, 12, 13], [14, 15, 16]])
y = np.array([[21, 22, 23], [24, 25, 26], [27, 28, 29]])
z = np.array([[31, 32, 33]])
arr = np.array([x, y, z])

In [18]:
print(arr)

[array([[11, 12, 13],
       [14, 15, 16]])
 array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])
 array([[31, 32, 33]])]


# Check shape

In [28]:
arr.size

3

In [20]:
arr.shape

(3,)

In [21]:
arr[0].shape

(2, 3)

In [22]:
arr[1].shape

(3, 3)

# convert forward and backward

In [23]:
np.vstack(arr)

array([[11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [31, 32, 33]])

In [27]:
tmp = arr
tmp = np.vstack(tmp)
tmp = np.split(tmp, [2, 5])
tmp = np.array(tmp)
print("===== Results =====")
print(tmp)
print("\n===== Original array =====")
print(arr)

===== Results =====
[array([[11, 12, 13],
       [14, 15, 16]])
 array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])
 array([[31, 32, 33]])]

===== Original array =====
[array([[11, 12, 13],
       [14, 15, 16]])
 array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])
 array([[31, 32, 33]])]


In [31]:
[tmp.shape[0] for tmp in arr]

[2, 3, 1]

In [35]:
np.cumsum([tmp.shape[0] for tmp in arr])[:-1]

array([2, 5])

In [37]:
idx = np.cumsum([tmp.shape[0] for tmp in arr])[:-1]

tmp = arr
tmp = np.vstack(tmp)
tmp = np.split(tmp, idx)
tmp = np.array(tmp)
print("===== Results =====")
print(tmp)
print("\n===== Original array =====")
print(arr)

===== Results =====
[array([[11, 12, 13],
       [14, 15, 16]])
 array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])
 array([[31, 32, 33]])]

===== Original array =====
[array([[11, 12, 13],
       [14, 15, 16]])
 array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])
 array([[31, 32, 33]])]
