In [1]:
import numpy as np

from toolz import curry

from sklearn.pipeline      import Pipeline
from sklearn.pipeline      import FeatureUnion
from sklearn.preprocessing import FunctionTransformer

In [9]:
@curry
def get_k_column(X, k = 0):
    return X[:, k:k+1]

@curry
def get_k_row(X, k = 6):
    return X[:k, :]

In [5]:
X = np.random.randn(5, 5)

In [14]:
print(X)
print("==========")
print(get_k_column(k = 0)(X))
print("==========")
print(get_k_column(k = 1)(X))
print("==========")
print(get_k_row(k = 3)(X))

[[ 0.3764962  -0.78052591 -1.01310915 -0.20685905 -0.29203923]
 [ 1.34415119 -0.90207403 -1.10036878 -0.2787732   0.57052235]
 [-1.36211133 -1.01789    -0.96182592  0.67002618  0.23698224]
 [-0.29056166  0.24414599 -0.1660865   0.69560355 -0.61796607]
 [ 0.68259925  0.5488471   0.04558598 -2.11361428  0.10420734]]
[[ 0.3764962 ]
 [ 1.34415119]
 [-1.36211133]
 [-0.29056166]
 [ 0.68259925]]
[[-0.78052591]
 [-0.90207403]
 [-1.01789   ]
 [ 0.24414599]
 [ 0.5488471 ]]
[[ 0.3764962  -0.78052591 -1.01310915 -0.20685905 -0.29203923]
 [ 1.34415119 -0.90207403 -1.10036878 -0.2787732   0.57052235]
 [-1.36211133 -1.01789    -0.96182592  0.67002618  0.23698224]]


In [18]:
pipe01 = FeatureUnion([
    ("column_0", FunctionTransformer(get_k_column)), 
    ("column_3", FunctionTransformer(get_k_column(k = 3)))])

pipe = Pipeline([
    ("column_0_3", pipe01), 
    ("row_3",      FunctionTransformer(get_k_row(k = 3)))])

In [19]:
print(X)
print("===================")
print(pipe.fit_transform(X))

[[ 0.3764962  -0.78052591 -1.01310915 -0.20685905 -0.29203923]
 [ 1.34415119 -0.90207403 -1.10036878 -0.2787732   0.57052235]
 [-1.36211133 -1.01789    -0.96182592  0.67002618  0.23698224]
 [-0.29056166  0.24414599 -0.1660865   0.69560355 -0.61796607]
 [ 0.68259925  0.5488471   0.04558598 -2.11361428  0.10420734]]
[[ 0.3764962  -0.20685905]
 [ 1.34415119 -0.2787732 ]
 [-1.36211133  0.67002618]]


# What if two output is not the same

In [20]:
pipe = FeatureUnion([
    ("column_0", FunctionTransformer(get_k_column)), 
    ("row_3",    FunctionTransformer(get_k_row(k = 3)))])

In [21]:
print(X)
print("===================")
print(pipe.fit_transform(X))

[[ 0.3764962  -0.78052591 -1.01310915 -0.20685905 -0.29203923]
 [ 1.34415119 -0.90207403 -1.10036878 -0.2787732   0.57052235]
 [-1.36211133 -1.01789    -0.96182592  0.67002618  0.23698224]
 [-0.29056166  0.24414599 -0.1660865   0.69560355 -0.61796607]
 [ 0.68259925  0.5488471   0.04558598 -2.11361428  0.10420734]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly